import { useState, useEffect } from "react";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Badge } from "@/components/ui/badge";
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { ScrollArea } from "@/components/ui/scroll-area";
import { 
  FileText, 
  Download, 
  Eye, 
  Calendar,
  AlertTriangle,
  Shield,
  Target,
  BarChart3,
  Filter,
  Search,
  Code2,
  FileCode
} from "lucide-react";
import { Input } from "@/components/ui/input";
import { supabase } from "@/integrations/supabase/client";
import { useToast } from "@/hooks/use-toast";

interface ScanReport {
  id: string;
  created_at: string;
  user_id: string;
  target: string;
  scan_type: string;
  vulnerability_name: string | null;
  severity: string | null;
  proof_of_concept: string | null;
  request_data: string | null;
  response_data: string | null;
  scan_output: string | null;
}

const VAPTReports = () => {
  const [reports, setReports] = useState<ScanReport[]>([]);
  const [selectedReport, setSelectedReport] = useState<ScanReport | null>(null);
  const [filterScanType, setFilterScanType] = useState<string>("all");
  const [filterSeverity, setFilterSeverity] = useState<string>("all");
  const [searchTerm, setSearchTerm] = useState("");
  const [loading, setLoading] = useState(true);
  const { toast } = useToast();

  useEffect(() => {
    fetchReports();
  }, []);

  const fetchReports = async () => {
    try {
      setLoading(true);
      const { data, error } = await supabase
        .from('scan_reports')
        .select('*')
        .order('created_at', { ascending: false });

      if (error) throw error;
      setReports(data || []);
    } catch (error: any) {
      console.error('Error fetching reports:', error);
      toast({
        title: "Error Loading Reports",
        description: error.message,
        variant: "destructive"
      });
    } finally {
      setLoading(false);
    }
  };

  const filteredReports = reports.filter(report => {
    const matchesScanType = filterScanType === "all" || report.scan_type === filterScanType;
    const matchesSeverity = filterSeverity === "all" || report.severity === filterSeverity;
    const matchesSearch = report.target.toLowerCase().includes(searchTerm.toLowerCase()) ||
                         (report.vulnerability_name?.toLowerCase().includes(searchTerm.toLowerCase()));
    
    return matchesScanType && matchesSeverity && matchesSearch;
  });

  const getSeverityColor = (severity: string) => {
    switch (severity) {
      case 'critical': return 'bg-red-500 text-white';
      case 'high': return 'bg-orange-500 text-white';
      case 'medium': return 'bg-yellow-500 text-black';
      case 'low': return 'bg-green-500 text-white';
      default: return 'bg-gray-500 text-white';
    }
  };

  const getStatusColor = (status: string) => {
    switch (status) {
      case 'completed': return 'bg-green-500 text-white';
      case 'in_progress': return 'bg-blue-500 text-white';
      case 'failed': return 'bg-red-500 text-white';
      default: return 'bg-gray-500 text-white';
    }
  };

  const downloadReport = (report: ScanReport) => {
    const reportContent = `# VAPT Scan Report - ${report.target}

## Scan Information
- **Target**: ${report.target}
- **Scan Type**: ${report.scan_type.toUpperCase()}
- **Scan Date**: ${new Date(report.created_at).toLocaleString()}
- **Report ID**: ${report.id}

${report.vulnerability_name ? `## Vulnerability Found
- **Name**: ${report.vulnerability_name}
- **Severity**: ${report.severity?.toUpperCase() || 'N/A'}` : ''}

${report.proof_of_concept ? `## Proof of Concept (POC)
\`\`\`
${report.proof_of_concept}
\`\`\`` : ''}

${report.request_data ? `## HTTP Request
\`\`\`http
${report.request_data}
\`\`\`` : ''}

${report.response_data ? `## HTTP Response
\`\`\`http
${report.response_data}
\`\`\`` : ''}

${report.scan_output ? `## Full Scan Output
\`\`\`
${report.scan_output}
\`\`\`` : ''}

---
Generated by CyberScope Scanner
© 2024 Harsh Malik - All Rights Reserved
`;

    const blob = new Blob([reportContent], { type: 'text/markdown' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `VAPT_Report_${report.scan_type}_${report.target.replace(/[^a-z0-9]/gi, '_')}_${report.id.substring(0, 8)}.md`;
    document.body.appendChild(a);
    a.click();
    document.body.removeChild(a);
    URL.revokeObjectURL(url);
  };

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <h2 className="text-3xl font-bold tracking-tight">VAPT Reports</h2>
        <div className="flex items-center space-x-2">
          <Badge variant="outline" className="text-sm">
            Total Reports: {reports.length}
          </Badge>
        </div>
      </div>

      {/* Filters */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Filter className="h-5 w-5 mr-2" />
            Filters
          </CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-1 md:grid-cols-4 gap-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Search</label>
              <div className="relative">
                <Search className="h-4 w-4 absolute left-3 top-3 text-muted-foreground" />
                <Input
                  placeholder="Search endpoints..."
                  value={searchTerm}
                  onChange={(e) => setSearchTerm(e.target.value)}
                  className="pl-9"
                />
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Scan Type</label>
              <Select value={filterScanType} onValueChange={setFilterScanType}>
                <SelectTrigger>
                  <SelectValue placeholder="All Scan Types" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Scan Types</SelectItem>
                  <SelectItem value="nmap">Nmap</SelectItem>
                  <SelectItem value="nikto">Nikto</SelectItem>
                  <SelectItem value="sqlmap">SQLMap</SelectItem>
                  <SelectItem value="gobuster">Gobuster</SelectItem>
                  <SelectItem value="nuclei">Nuclei</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Severity</label>
              <Select value={filterSeverity} onValueChange={setFilterSeverity}>
                <SelectTrigger>
                  <SelectValue placeholder="All Severities" />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="all">All Severities</SelectItem>
                  <SelectItem value="critical">Critical</SelectItem>
                  <SelectItem value="high">High</SelectItem>
                  <SelectItem value="medium">Medium</SelectItem>
                  <SelectItem value="low">Low</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Actions</label>
              <Button variant="outline" className="w-full">
                <BarChart3 className="h-4 w-4 mr-2" />
                Export Summary
              </Button>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Reports Grid */}
      {loading ? (
        <Card>
          <CardContent className="p-12 text-center">
            <p className="text-muted-foreground">Loading reports...</p>
          </CardContent>
        </Card>
      ) : filteredReports.length === 0 ? (
        <Card>
          <CardContent className="p-12 text-center">
            <FileText className="h-16 w-16 mx-auto mb-4 text-muted-foreground opacity-50" />
            <p className="text-lg font-medium mb-2">No Reports Found</p>
            <p className="text-muted-foreground">
              Run security scans to generate VAPT reports with detailed findings
            </p>
          </CardContent>
        </Card>
      ) : (
        <div className="grid gap-6">
          {filteredReports.map((report) => (
            <Card key={report.id} className="hover:shadow-lg transition-shadow">
              <CardHeader>
                <div className="flex items-center justify-between">
                  <div className="flex items-center space-x-3">
                    <Target className="h-6 w-6 text-primary" />
                    <div>
                      <CardTitle className="text-lg">{report.target}</CardTitle>
                      <p className="text-sm text-muted-foreground">
                        {report.scan_type.toUpperCase()} • {new Date(report.created_at).toLocaleString()}
                      </p>
                    </div>
                  </div>
                  <div className="flex items-center space-x-2">
                    {report.severity && (
                      <Badge className={getSeverityColor(report.severity)}>
                        {report.severity.toUpperCase()}
                      </Badge>
                    )}
                    <Badge variant="outline">{report.scan_type}</Badge>
                  </div>
                </div>
              </CardHeader>
              <CardContent>
                <div className="space-y-4">
                  <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
                    <div className="space-y-1">
                      <p className="text-sm font-medium">Vulnerability</p>
                      <p className="text-sm text-muted-foreground">
                        {report.vulnerability_name || 'N/A'}
                      </p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm font-medium">POC Available</p>
                      <p className="text-sm text-muted-foreground">
                        {report.proof_of_concept ? '✅ Yes' : '❌ No'}
                      </p>
                    </div>
                    <div className="space-y-1">
                      <p className="text-sm font-medium">Request/Response</p>
                      <p className="text-sm text-muted-foreground">
                        {report.request_data || report.response_data ? '✅ Captured' : '❌ None'}
                      </p>
                    </div>
                  </div>

                  <div className="flex justify-between items-center pt-4 border-t">
                    <div className="flex space-x-2">
                      <Dialog>
                        <DialogTrigger asChild>
                          <Button 
                            size="sm" 
                            variant="outline"
                            onClick={() => setSelectedReport(report)}
                          >
                            <Eye className="h-4 w-4 mr-1" />
                            View Details
                          </Button>
                        </DialogTrigger>
                        <DialogContent className="max-w-4xl max-h-[80vh]">
                          <DialogHeader>
                            <DialogTitle>
                              VAPT Report - {selectedReport?.target}
                            </DialogTitle>
                          </DialogHeader>
                          <ScrollArea className="h-[60vh]">
                            {selectedReport && (
                              <div className="space-y-6 pr-4">
                                <div className="grid grid-cols-2 gap-4">
                                  <div>
                                    <h4 className="font-semibold mb-2 flex items-center">
                                      <Target className="h-4 w-4 mr-2" />
                                      Scan Information
                                    </h4>
                                    <div className="space-y-1 text-sm">
                                      <p><strong>Target:</strong> {selectedReport.target}</p>
                                      <p><strong>Scan Type:</strong> {selectedReport.scan_type.toUpperCase()}</p>
                                      <p><strong>Date:</strong> {new Date(selectedReport.created_at).toLocaleString()}</p>
                                      <p><strong>Report ID:</strong> {selectedReport.id.substring(0, 8)}...</p>
                                    </div>
                                  </div>
                                  <div>
                                    <h4 className="font-semibold mb-2 flex items-center">
                                      <AlertTriangle className="h-4 w-4 mr-2" />
                                      Vulnerability Details
                                    </h4>
                                    <div className="space-y-1 text-sm">
                                      <p><strong>Name:</strong> {selectedReport.vulnerability_name || 'N/A'}</p>
                                      {selectedReport.severity && (
                                        <p><strong>Severity:</strong> 
                                          <Badge className={`ml-2 ${getSeverityColor(selectedReport.severity)}`}>
                                            {selectedReport.severity}
                                          </Badge>
                                        </p>
                                      )}
                                    </div>
                                  </div>
                                </div>

                                {selectedReport.proof_of_concept && (
                                  <div>
                                    <h4 className="font-semibold mb-2 flex items-center">
                                      <Code2 className="h-4 w-4 mr-2" />
                                      Proof of Concept (POC)
                                    </h4>
                                    <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
                                      {selectedReport.proof_of_concept}
                                    </pre>
                                  </div>
                                )}

                                {selectedReport.request_data && (
                                  <div>
                                    <h4 className="font-semibold mb-2 flex items-center">
                                      <FileCode className="h-4 w-4 mr-2" />
                                      HTTP Request
                                    </h4>
                                    <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
                                      {selectedReport.request_data}
                                    </pre>
                                  </div>
                                )}

                                {selectedReport.response_data && (
                                  <div>
                                    <h4 className="font-semibold mb-2 flex items-center">
                                      <FileCode className="h-4 w-4 mr-2" />
                                      HTTP Response
                                    </h4>
                                    <pre className="bg-muted p-4 rounded-lg text-sm overflow-x-auto">
                                      {selectedReport.response_data}
                                    </pre>
                                  </div>
                                )}

                                {selectedReport.scan_output && (
                                  <div>
                                    <h4 className="font-semibold mb-2 flex items-center">
                                      <FileText className="h-4 w-4 mr-2" />
                                      Full Scan Output
                                    </h4>
                                    <ScrollArea className="h-[300px]">
                                      <pre className="bg-muted p-4 rounded-lg text-xs">
                                        {selectedReport.scan_output}
                                      </pre>
                                    </ScrollArea>
                                  </div>
                                )}
                              </div>
                            )}
                          </ScrollArea>
                        </DialogContent>
                      </Dialog>
                      <Button size="sm" onClick={() => downloadReport(report)}>
                        <Download className="h-4 w-4 mr-1" />
                        Download
                      </Button>
                    </div>
                    <div className="flex items-center text-sm text-muted-foreground">
                      <Calendar className="h-4 w-4 mr-1" />
                      {new Date(report.created_at).toLocaleString()}
                    </div>
                  </div>
                </div>
              </CardContent>
            </Card>
          ))}
        </div>
      )}
    </div>
  );
};

export default VAPTReports;